#!/usr/bin/env python
import sys
import pkuseg
seg = pkuseg.pkuseg() 
# use stdin if it's full                                                        
# data = sys.argv[1]
if not sys.stdin.isatty():
    data = sys.stdin.read()
segmentedText = seg.cut(data) 
for word in segmentedText:
    print(word, end=" ")
