#!/usr/bin/env python
import sys
import tltk


# use stdin if it's full                                                        
if not sys.stdin.isatty():
    data = sys.stdin.read()
segmentedText = tltk.nlp.word_segment(data).replace("|"," ").replace(" <s/>","")
print(segmentedText)
