set-window-option -g mode-keys vi
list-keys -T copy-mode-vi

# Use vi bindings in copy mode
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Allow using arrow keys to navigate in copy mode
bind -T copy-mode-vi 'k' send -X cursor-up
bind -T copy-mode-vi 'j' send -X cursor-down
bind -T copy-mode-vi 'h' send -X cursor-left
bind -T copy-mode-vi 'l' send -X cursor-right

# Enable vi scrolling
bind -T copy-mode-vi 'PageUp' send -X page-up
bind -T copy-mode-vi 'PageDown' send -X page-down
bind -T copy-mode-vi 'H' send -X start-of-line
bind -T copy-mode-vi 'L' send -X end-of-line
bind -T copy-mode-vi 'w' send -X next-word
bind -T copy-mode-vi 'b' send -X previous-word
bind -T copy-mode-vi '0' send -X start-of-line
bind -T copy-mode-vi '$' send -X end-of-line
bind -T copy-mode-vi '/' command-prompt "-psearch up" "send -X search-backward-incremental \"%%%\""
bind -T copy-mode-vi '?' command-prompt "-psearch down" "send -X search-forward-incremental \"%%%\""
